CREATE DEFINER=`root`@`localhost` PROCEDURE `rate_suppliers`()
BEGIN
SELECT s.SUPP_ID, s.SUPP_NAME, r.RAT_RATSTARS,
CASE
WHEN r.RAT_RATSTARS > 4 THEN 'GENUINE SUPPLIERS'
WHEN r.RAT_RATSTARS > 2 THEN 'AVERAGE SUPPLIERS'
ELSE 'SUPPLIER SHOULD NOT BE CONSIDERED'
END AS VERDICT FROM Rating r INNER JOIN Supplier s ON s.SUPP_ID=r.SUPP_ID;
END